# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detects unused variable assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused code

    # Additional linters
    - bodyclose     # Check HTTP response body is closed
    - contextcheck  # Check context.Context is passed correctly
    - durationcheck # Check for two durations multiplied together
    - errname       # Check error names follow Go conventions
    - errorlint     # Check error handling follows best practices
    - exhaustive    # Check exhaustiveness of enum switch statements
    - exportloopref # Check for pointers to loop variables
    - gocognit      # Check cognitive complexity
    - goconst       # Find repeated strings that could be constants
    - gocritic      # Comprehensive linter
    - gocyclo       # Check cyclomatic complexity
    - godot         # Check comments end with period
    - gofmt         # Check code is formatted
    - goimports     # Check imports are organized
    - gosec         # Security checker
    - misspell      # Find misspelled words
    - nilerr        # Check nil error is returned
    - noctx         # Check HTTP requests use context
    - prealloc      # Find slice declarations that could be preallocated
    - predeclared   # Find shadowed predeclared identifiers
    - revive        # Fast, configurable, extensible linter
    - sqlclosecheck # Check SQL Rows are closed
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
    - wastedassign  # Find wasted assignment statements

  disable:
    - depguard      # We manage deps ourselves
    - funlen        # Function length - too strict
    - gochecknoglobals # We use some globals for errors
    - gomnd         # Magic number detector - too noisy
    - lll           # Line length - handled by formatter
    - wsl           # Whitespace linter - too strict

linters-settings:
  errcheck:
    # Check for type assertions
    check-type-assertions: true
    # Check for blank identifier assignments
    check-blank: true
    # Ignore specific functions
    exclude-functions:
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too strict for our use case

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - hugeParam  # We pass some large structs by value intentionally

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/tathienbao/quant-bot

  gosec:
    excludes:
      - G104  # Audit errors not checked - we use errcheck
      - G304  # File path provided as taint input - we control our paths

  misspell:
    locale: US

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  staticcheck:
    checks:
      - all
      - -SA1019  # Deprecated - we'll handle manually

  unparam:
    check-exported: false

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 50

  # Maximum count of issues with the same text
  max-same-issues: 10

  # Don't hide issues in vendor, third-party, generated files
  exclude-dirs:
    - vendor
    - third_party
    - testdata
    - examples

  # Exclude some linters from running on tests files
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - errcheck
        - dupl
        - gosec
        - unparam

    # Exclude known issues in generated files
    - path: mock_
      linters:
        - all

    # Exclude shadow check for err variable (common pattern)
    - linters:
        - govet
      text: 'shadow: declaration of "err"'

    # Allow error string formatting
    - linters:
        - goerr113
      text: "do not define dynamic errors"

severity:
  default-severity: warning
  rules:
    - linters:
        - gosec
      severity: error
    - linters:
        - errcheck
      severity: error
