# golangci-lint configuration (v2)
version: "2"

run:
  timeout: 5m
  tests: false

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
  settings:
    govet:
      disable:
        - fieldalignment
        - shadow
    staticcheck:
      checks:
        - all
        - "-SA1019"
        - "-QF1003"
        - "-QF1007"
        - "-ST1000"
