// Package metrics provides Prometheus metrics for the trading bot.
package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// Trading metrics
var (
	// OrdersTotal counts total orders by side and status.
	OrdersTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: "quantbot",
			Subsystem: "trading",
			Name:      "orders_total",
			Help:      "Total number of orders by side and status",
		},
		[]string{"symbol", "side", "status"},
	)

	// TradesTotal counts total completed trades by side and outcome.
	TradesTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: "quantbot",
			Subsystem: "trading",
			Name:      "trades_total",
			Help:      "Total number of completed trades by side and outcome",
		},
		[]string{"symbol", "side", "outcome"},
	)

	// PositionsOpen tracks currently open positions.
	PositionsOpen = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Namespace: "quantbot",
			Subsystem: "trading",
			Name:      "positions_open",
			Help:      "Number of currently open positions",
		},
		[]string{"symbol"},
	)

	// PositionContracts tracks contracts in open positions.
	PositionContracts = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Namespace: "quantbot",
			Subsystem: "trading",
			Name:      "position_contracts",
			Help:      "Number of contracts in open positions",
		},
		[]string{"symbol", "side"},
	)
)

// Account metrics
var (
	// EquityCurrent tracks the current account equity.
	EquityCurrent = promauto.NewGauge(
		prometheus.GaugeOpts{
			Namespace: "quantbot",
			Subsystem: "account",
			Name:      "equity_current",
			Help:      "Current account equity in USD",
		},
	)

	// EquityHighWaterMark tracks the peak equity value.
	EquityHighWaterMark = promauto.NewGauge(
		prometheus.GaugeOpts{
			Namespace: "quantbot",
			Subsystem: "account",
			Name:      "equity_high_water_mark",
			Help:      "Peak account equity (high water mark) in USD",
		},
	)

	// DrawdownCurrent tracks the current drawdown percentage.
	DrawdownCurrent = promauto.NewGauge(
		prometheus.GaugeOpts{
			Namespace: "quantbot",
			Subsystem: "account",
			Name:      "drawdown_current",
			Help:      "Current drawdown as a ratio (0.0 to 1.0)",
		},
	)

	// DailyPL tracks the daily profit/loss.
	DailyPL = promauto.NewGauge(
		prometheus.GaugeOpts{
			Namespace: "quantbot",
			Subsystem: "account",
			Name:      "daily_pl",
			Help:      "Daily profit/loss in USD",
		},
	)

	// TotalPL tracks the total profit/loss.
	TotalPL = promauto.NewGauge(
		prometheus.GaugeOpts{
			Namespace: "quantbot",
			Subsystem: "account",
			Name:      "total_pl",
			Help:      "Total profit/loss in USD",
		},
	)
)

// Risk metrics
var (
	// SafeModeActive indicates if safe mode is active (1) or not (0).
	SafeModeActive = promauto.NewGauge(
		prometheus.GaugeOpts{
			Namespace: "quantbot",
			Subsystem: "risk",
			Name:      "safe_mode_active",
			Help:      "Whether safe mode (kill switch) is active (1=yes, 0=no)",
		},
	)

	// SignalsGenerated counts signals generated by strategy.
	SignalsGenerated = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: "quantbot",
			Subsystem: "risk",
			Name:      "signals_generated_total",
			Help:      "Total signals generated by strategy",
		},
		[]string{"strategy", "side"},
	)

	// SignalsRejected counts signals rejected by risk engine.
	SignalsRejected = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: "quantbot",
			Subsystem: "risk",
			Name:      "signals_rejected_total",
			Help:      "Total signals rejected by risk engine",
		},
		[]string{"reason"},
	)
)

// Latency metrics
var (
	// OrderLatency tracks order execution latency.
	OrderLatency = promauto.NewHistogram(
		prometheus.HistogramOpts{
			Namespace: "quantbot",
			Subsystem: "latency",
			Name:      "order_execution_seconds",
			Help:      "Order execution latency in seconds",
			Buckets:   []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10},
		},
	)

	// DataFeedLatency tracks market data feed latency.
	DataFeedLatency = promauto.NewHistogram(
		prometheus.HistogramOpts{
			Namespace: "quantbot",
			Subsystem: "latency",
			Name:      "data_feed_seconds",
			Help:      "Market data feed latency in seconds",
			Buckets:   []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1},
		},
	)

	// StrategyLatency tracks strategy computation latency.
	StrategyLatency = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Namespace: "quantbot",
			Subsystem: "latency",
			Name:      "strategy_seconds",
			Help:      "Strategy computation latency in seconds",
			Buckets:   []float64{0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1},
		},
		[]string{"strategy"},
	)
)

// System metrics
var (
	// HeartbeatTimestamp tracks the last heartbeat time.
	HeartbeatTimestamp = promauto.NewGauge(
		prometheus.GaugeOpts{
			Namespace: "quantbot",
			Subsystem: "system",
			Name:      "heartbeat_timestamp",
			Help:      "Unix timestamp of last heartbeat",
		},
	)

	// DataFeedConnected indicates if data feed is connected.
	DataFeedConnected = promauto.NewGauge(
		prometheus.GaugeOpts{
			Namespace: "quantbot",
			Subsystem: "system",
			Name:      "data_feed_connected",
			Help:      "Whether data feed is connected (1=yes, 0=no)",
		},
	)

	// BrokerConnected indicates if broker is connected.
	BrokerConnected = promauto.NewGauge(
		prometheus.GaugeOpts{
			Namespace: "quantbot",
			Subsystem: "system",
			Name:      "broker_connected",
			Help:      "Whether broker is connected (1=yes, 0=no)",
		},
	)

	// UptimeSeconds tracks bot uptime.
	UptimeSeconds = promauto.NewCounter(
		prometheus.CounterOpts{
			Namespace: "quantbot",
			Subsystem: "system",
			Name:      "uptime_seconds_total",
			Help:      "Total uptime in seconds",
		},
	)

	// ErrorsTotal counts errors by type.
	ErrorsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: "quantbot",
			Subsystem: "system",
			Name:      "errors_total",
			Help:      "Total errors by type",
		},
		[]string{"type"},
	)
)

// Info metric for build information
var (
	BuildInfo = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Namespace: "quantbot",
			Name:      "build_info",
			Help:      "Build information",
		},
		[]string{"version", "commit", "build_time"},
	)
)

// SetBuildInfo sets the build information metric.
func SetBuildInfo(version, commit, buildTime string) {
	BuildInfo.WithLabelValues(version, commit, buildTime).Set(1)
}
